[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/demo"

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
